[project]
name = "skt-ai-summit-hackathon-2025-pre-mission"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.5",
]
